// <auto-generated />
using System;
using GitSight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitSight.Infrastructure.Migrations
{
    [DbContext(typeof(GitSightDbContext))]
    [Migration("20261010164407_InitialNeonDb")]
    partial class InitialNeonDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitSight.Domain.Entities.AiReviewIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiReviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.Property<string>("SuggestedAddedCode")
                        .HasColumnType("text");

                    b.Property<string>("SuggestedRemovedCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiReviewSessionId");

                    b.ToTable("AiReviewIssues");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.AiReviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BreachesCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeComplexity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CodeSmellsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FinalSuggestionsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebhook")
                        .HasColumnType("boolean");

                    b.Property<decimal>("OverallConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerformanceIssuesCount")
                        .HasColumnType("integer");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SecurityIssuesCount")
                        .HasColumnType("integer");

                    b.Property<int>("SyntaxErrorsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TestCoverageImpact")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AiReviewSessions");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.PrInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryFullName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryFullName", "PrNumber")
                        .IsUnique();

                    b.ToTable("PrInsights");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiffContent")
                        .HasColumnType("text");

                    b.Property<string>("HeadBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PrNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "PrNumber")
                        .IsUnique();

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("GitHubRepoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long?>("WebhookId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GitHubRepoId");

                    b.HasIndex("UserId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.ReviewComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPostedToGitHub")
                        .HasColumnType("boolean");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PrInsightId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SuggestedCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrInsightId");

                    b.ToTable("ReviewComments");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.TrackedIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiReviewIssueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuggestedAddedCode")
                        .HasColumnType("text");

                    b.Property<string>("SuggestedRemovedCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TrackedIssues");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.AiReviewIssue", b =>
                {
                    b.HasOne("GitSight.Domain.Entities.AiReviewSession", "Session")
                        .WithMany("Issues")
                        .HasForeignKey("AiReviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.PullRequest", b =>
                {
                    b.HasOne("GitSight.Domain.Entities.Repository", "Repository")
                        .WithMany("PullRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.Repository", b =>
                {
                    b.HasOne("GitSight.Domain.Entities.User", "User")
                        .WithMany("Repositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.ReviewComment", b =>
                {
                    b.HasOne("GitSight.Domain.Entities.PrInsight", "PrInsight")
                        .WithMany("Comments")
                        .HasForeignKey("PrInsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrInsight");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.AiReviewSession", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.PrInsight", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.Repository", b =>
                {
                    b.Navigation("PullRequests");
                });

            modelBuilder.Entity("GitSight.Domain.Entities.User", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
